export const balanceReportData = [
  {
    sn: 1,
    date: "2025-07-24",
    particular: "BULK SMS",
    dr: "-1140",
    cr: "-",
    balance: "255.31",
    attachment: "-",
    user: "Aadim National College",
    sourceRemark: "-",
  },
  {
    sn: 2,
    date: "2025-07-24",
    particular: "GROUP SMS",
    dr: "-500",
    cr: "-",
    balance: "400.00",
    attachment: "-",
    user: "Aadim National College",
    sourceRemark: "-",
  },
  {
    sn: 3,
    date: "2025-07-24",
    particular: "SINGLE SMS",
    dr: "-2",
    cr: "-",
    balance: "398.00",
    attachment: "-",
    user: "Aadim National College",
    sourceRemark: "-",
  },
];
